server:
  port: 8877

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/niezhiliang/spring-cloud-archetype
          search-paths: conf
eureka:
  client:
    service-url:
      defaultZone: http://eureka:1234/eureka/

