suyu:
  name: "Hello World!"



#数据库库的配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nzl?useUnicode=true&characterEncoding=utf8
    username: root
    password: adminadmin
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver



#mybatits配置
mybatis:
  configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mappers/*Mapper.xml

#Redis配置
liumapp:
  redis:
    port: 6379
    hostName: 114.215.42.166
    password: huluwa890TJ
