suyu:
  name: "Hello Service B!"
  basedir: "/docker/personal/log.txt"



#数据库库的配置
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: huluwa
    password: huluwa110
    publisher-confirms: true
    publisher-returns: true
  datasource:
    url: jdbc:mysql://www.niezhiliang.com:3306/suyu?useUnicode=true&characterEncoding=utf8
    username: root
    password: nzl199595
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver



#mybatits配置
mybatis:
  configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mappers/*Mapper.xml

#Redis配置
liumapp:
  redis:
    port: 6379
    hostName: 114.215.42.166
    password: huluwa890TJ
